// <auto-generated />
namespace AdminstrationSysytem_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class h11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(h11));
        
        string IMigrationMetadata.Id
        {
            get { return "201704082055434_h11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
